### ISSUE TITLE
DefaultButton animation causes crash in PikoPixel

### ISSUE THREAD

**Issue by BertrandDekoninck** [AlessandroSangiuliano/rik.theme#11]
See the following mail with Josh Freeman, PikoPixel's author: 

On Oct 15, 2018, at 12:09 PM, Bertrand Dekoninck wrote:
 […]

Since revision beta9a, Pikopixel segfaults on dry launch, right after that I push the OK button of the first dialog (creating an empty window). It doesn't occur when I open an image with it (using the context menu of GWorkspace).

  Thanks for this info. I can reproduce the crash, and it appears to be a bug in Rik.theme (I used the fork at https://github.com/BertrandDekoninck/rik.theme ):

  Rik.theme replaces the implementation of -[NSWindow setDefaultButtonCell:] in order to set up an animation that pulses the window's default button. Rik.theme's animation controller retains the default button cell that was passed, and the animation will continuously call [[defaultbuttoncell controlview] setNeedsDisplay: YES] to update the button.

  However, the animation is never stopped, so it will continue sending setNeedsDisplay: messages even after the window is ordered out, up until the app exits (for every default button that's been displayed).

  If a window is unloaded (several of PikoPixel's sheets are released once they're dismissed, including its initial size sheet), the default button cell will stick around, since the animation controller retained it, but the cell will contain a pointer to a now-deallocated control view (NSActionCells don't retain their control views, presumably to prevent retain loops), and sending it a setNeedsDisplay: message will crash.

  To show this is the cause of the issue, you can prevent the control view from deallocating by retaining it as well - change rik.theme's NSWindow+Rik.m, line 35:

       [[defaultbuttoncell controlview] setNeedsDisplay: YES];
->
       [[[defaultbuttoncell controlview] retain] setNeedsDisplay: YES];

  (Note that this is just for demonstration, and not a fix, since it will leak the control view & run up its retain count. A fix would probably involve registering for NSWindowDidResignKey notifications and stopping animation when the notification was received).

Cheers,

Josh

**Comment by AlessandroSangiuliano** [comment]
Is someone can test PicoPixel with the new fix I merged I can close this issue. 

Thank You.

**Comment by BertrandDekoninck** [comment]
Pikopixel works as it should now. You can close.
